### PR TITLE
Check for message key case validity (Fixes #56)

### LINKED ISSUE #56: Check for message key case validity
Per <https://gerrit.wikimedia.org/r/#/c/338932/>, fail if the message key does not start with a lowercase character.

### PR DESCRIPTION
**Pull request by jdforrester**
Fixes #56.

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -60,6 +60,18 @@ module.exports = function ( grunt ) {
 						'fourth-message-key'
 					]
 				}
+			},
+			requireInitialLowerCase: {
+				src: 'test/requireLowerCase/initial',
```
Comment (Krinkle) [inline Gruntfile.js]: May need to `git add test/requireLowerCase`.

File: Gruntfile.js [hunk 2]
```diff
@@ -60,6 +60,18 @@ module.exports = function ( grunt ) {
...
+				options: {
+					requireLowerCase: 'initial'
+				}
+			},
+			requireFullLowerCase: {
+				src: 'test/requireLowerCase/full',
```
Comment (Krinkle) [inline Gruntfile.js]: I haven't seen the contents yet, but imho the name "require full lower case" implies it as a step up from "require initial lower case", but the config of `false` suggests this test case is likely more to be an "allow mixed case" test, which I'd expect would include a key that starts with upper case and intended to pass the test (given `false`).

The test case for requiring all-lowercase, is presumably left out because all other tests cover that already. That's fine :)

Comment (jdforrester) [reply Gruntfile.js]: > The test case for requiring all-lowercase, is presumably left out because all other tests cover that already. That's fine :)

Yeah, see #10. :-(

Comment (Krinkle) [reply Gruntfile.js]: Right, so this is intended to be a test suite for asserting failure when `requireLowerCase: true`, except you can't do that because it would fail the build. I see.

It would still be useful to also assert that mixed case is allowed (does not fail) when `requireLowerCase: false`, which is what this currently asserts, albeit unintentionally.

Could you rename it to allowMixedCase or some such, or in current state, add a comment to indicate that this is meant to be a failing test with `requireLowerCase: true` in the future?

Comment (jdforrester) [reply Gruntfile.js]: > It would still be useful to also assert that mixed case is allowed (does not fail) when `requireLowerCase: false`, which is what this currently asserts, albeit unintentionally.

It's intentionally asserted in the `requireInitialLowerCase` suite.

Happy to rename the suites.

**Comment by Krinkle** [comment]
Sorry for not squashing. I didn't due to the package bump commit, but forgot that there were also 2 fixup commits.

With GitHub's flow, I'd normally either have two separate PRs (drawback of having to keep two local branches in sync, and manually both and then push both), or - slightly easier - to amend existing commit and force push the branch, which is more the Gerrit-style.

Neither of these works through the GitHub web interface, though. The web interface is fine as long as we squash, which means we can't have the same PR build up two final commits; unless the commit is made locally instead of in the web editor.

**Comment by jdforrester** [comment]
Merge is I think better than squashing (but GH's lack of happiness with amends is an evergreen irritant). No worries.
